version: 2

builds:
  - id: envolve
    builder: rust
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "envolve_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

brews:
  - repository:
      owner: mb4ndeira
      name: homebrew-tap
    commit_author:
      name: Matheus Bandeira
      email: matheus.bandeira@inovahu.com
    directory: Formula
    homepage: https://github.com/mb4ndeira/envolve
    description: Env schema validator and .env.example generator
    license: MIT
    install: bin.install "envolve"
    test: system "#{bin}/envolve", "--version"

nfpms:
  - package_name: envolve
    homepage: https://github.com/mb4ndeira/envolve
    description: Env schema validator and .env.example generator
    license: MIT
    formats:
      - deb
      - rpm
      - apk

release:
  github:
    owner: mb4ndeira
    name: envolve
